### ISSUE TITLE
Add github ref & license note to code.

### ISSUE THREAD

**Issue by kwerle** [gpolak/LFHeatMap#2]
I'm avoiding 3rd party build tools, so I'll be incorporating LFHeatMap source files directly.

I'll be adding a link to the github repo at the top of the .h and .m files manually.  It'd be nice if they were already in there with a copyright and credit to you notice.

Thank you for your work!
Kurt

**Comment by gpolak** [comment]
Sounds good Kurt - headers added. Enjoy!
