### ISSUE TITLE
When you zoom into map (and therefore certain points are off screen) they should still be weighed in and not discarded...

### ISSUE THREAD

**Issue by janngobble** [gpolak/LFHeatMap#4]
I am using this to overlay a uiimage of heatmap over mapkit. Let's assume for a minute we are talking about a mkmapview of a city. I have points (busyness) for how many ppl are in certain locations...therefore the heatmap of those locations should be denser (brighter).  This works when all the points are visible on the main screen...but when you zoom in on a certain area, the busiest points of the city are no longer taken into account when calculating brightness of blobs.

ie: if you have a lot of ppl on top left of map, it is bright yellow with a red background, whereas a lower populated area in center of map is just red.  This is as it should be, BUT if i zoom in to center of map, the top left "weight" of the top left coordinates is not taken into account and now center of map is bright yellow. For purposes of brightness of each blob, each weight should always be taken into account. Changing map rect (or zoomlevel) should not change brightness of each section of heatmap.

I have no idea which section is in control of this however it SEEMS to be between 1.0 and 1.5 that is causing this (right after you copy the nsarray into array.  

Ideas on a fix?

**Comment by gpolak** [comment]
Try playing with the `weightsAdjustmentEnabled` and `groupingEnabled` values.

**Comment by janngobble** [comment]
This does not achieve the effect of "remembering" the thrown away values from Step 1 "Filter out range of points"...but i will work on it and post my findings.

Thanks!
