### ISSUE TITLE
need you help

### ISSUE THREAD

**Issue by 179992096** [gpolak/LFHeatMap#6]
![2015-09-30 16 29 17](https://cloud.githubusercontent.com/assets/11768708/10188253/77371c10-6790-11e5-9c96-bffd082706ef.png)

Hi , I have a question ，I want to achieve this effect(look attachment) . my english is not good ,but i need you  help. thinks

**Comment by gpolak** [comment]
See this: https://github.com/gpolak/LFHeatMap/issues/5

**Comment by 179992096** [comment]
bingo , problem solving , thinks
