### ISSUE TITLE
Swift

### ISSUE THREAD

**Issue by LeonardBonfils** [gpolak/LFHeatMap#8]
Hi there,

Would it be possible for you to translate your documentation in Swift ? That'd be very much appreciated.

Thanks :)

**Comment by janngobble** [comment]
Translating docs won’t help since LFHeatMap is in Obj-C, right?


Jann

**Comment by gpolak** [comment]
Hello, @janngobble is correct, the code is ObjectiveC and would need to be ported to Swift. You could also use a bridging header to use this in your Swift code: https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

**Comment by johndpope** [comment]
fyi - I came across this project https://github.com/shazlehu/SoilSampler/tree/Swift2/SoilSampler which includes a pure swift implementation of DTMHeatmap https://github.com/dataminr/DTMHeatmap. 
(Side Note - it seems to be a line by line port - but swift is much slower to render. )

**Comment by gpolak** [comment]
Thanks @johndpope, I've added a link to DTMHeatmap to the README.
